-- MySQL Script generated by MySQL Workbench
-- Thu Sep 25 09:28:20 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Players`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Players` (
    `player_id` INT NOT NULL AUTO_INCREMENT,
    `nickname` VARCHAR(30) NULL,
    `email` VARCHAR(100) NULL,
    `joined_at` DATETIME NULL,
    `country` VARCHAR(50) NULL,
    PRIMARY KEY (`player_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Payments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Payments` (
    `payment_id` INT NOT NULL AUTO_INCREMENT,
    `player_id` INT NOT NULL,
    `amount` INT NULL COMMENT '결제 금액 (KRW)	\n',
    `payment_method` ENUM('CARD', 'BANK', 'CASH', 'STORE') NULL,
    `paid_at` DATETIME NULL,
    `item_description` VARCHAR(100) NULL,
    PRIMARY KEY (`payment_id`),
    CONSTRAINT `fk_Payments_Players`
    FOREIGN KEY (`player_id`)
    REFERENCES `Players` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Payments_Players_idx` ON `Payments` (`player_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Games` (
    `game_id` INT NOT NULL AUTO_INCREMENT,
    `title` VARCHAR(100) NULL,
    `genre` VARCHAR(50) NULL,
    `release_date` DATE NULL,
    PRIMARY KEY (`game_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PlayHistories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PlayHistories` (
    `play_history_id` INT NOT NULL AUTO_INCREMENT,
    `player_id` INT NOT NULL,
    `game_id` INT NOT NULL,
    `started_at` DATETIME NULL,
    `ended_at` DATETIME NULL,
    PRIMARY KEY (`play_history_id`),
    CONSTRAINT `fk_PlayHistories_Games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `Games` (`game_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
    CONSTRAINT `fk_PlayHistories_Players1`
    FOREIGN KEY (`player_id`)
    REFERENCES `Players` (`player_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PlayHistories_Games1_idx` ON `PlayHistories` (`game_id` ASC) VISIBLE;

CREATE INDEX `fk_PlayHistories_Players1_idx` ON `PlayHistories` (`player_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Scores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Scores` (
    `score_id` INT NOT NULL AUTO_INCREMENT,
    `score` INT NULL,
    `result` ENUM('WIN', 'LOSE', 'DRAW') NULL,
    `play_history_id` INT NOT NULL,
    PRIMARY KEY (`score_id`, `play_history_id`),
    CONSTRAINT `fk_Scores_PlayHistories1`
    FOREIGN KEY (`play_history_id`)
    REFERENCES `PlayHistories` (`play_history_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Scores_PlayHistories1_idx` ON `Scores` (`play_history_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
